---
- name: systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd

- name: restart factorio
  ansible.builtin.systemd:
    name: factorio.service
    state: restarted
  listen: restart factorio
