# k8s/must-run/infrastructure/synology-csi/helmrelease.yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: synology-csi
  namespace: flux-system
spec:
  interval: 24h
  url: https://christian-schlichtherle.github.io/synology-csi-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: synology-csi
spec:
  interval: 30m
  chart:
    spec:
      chart: synology-csi
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: synology-csi
        namespace: flux-system
  install:
    createNamespace: false
  values:
    clientInfoSecret:
      name: synology-csi
    storageClasses:
      nfs-retain:
        disabled: true
      nfs-delete:
        disabled: true
      iscsi-retain:
        isDefault: true
        parameters:
          protocol: iscsi
          dsm: "10.0.254.20"
        reclaimPolicy: Retain
      iscsi-delete:
        disabled: true
      smb-retain:
        disabled: true
      smb-delete:
        disabled: true
