---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synology-csi
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yaml: AgCSq9UoewvMAwOr1jHbTr7AiX0vY1XFFh37GQT+oorrc6dTyeSVK3xPQ/kDe9IIl91wOpTnjNtRnPXpbdq/y1YJYJAWMy/wZQjUFl0+7zqh025F6lpDB4zThIgUXVP3uCz7a3t5e2G48Zd4BhydqR8IhBe7HCKGDy37SjKAuXqqMQ9d+oKmYTW2GKI+DGvwoHOAApkeVIyM+JIkuIoBYGqcUQbSvqyWRuRV9ykzaskWLPmeD5ntGuf4ACVkp1W4Kz9lxCJj+tWkimpxbcT1NAieeBbLSJ9TADS5eGrsO1Y174v7GAeT0py6m2yrisQMRgGFy9hx5G0tcXG9iLWMvNMiErSSRZc4h1KowSnKEX5igB+lgkdhEY9bZbg+hkC8Np56O7uDhMsmyLKSUoWza3hzrXj/GGVPXug4qpVTXv6+djPcXsJvfSY5Ngz6o7vNba/M1Q/yTMVJId4bkeycjWyCMhhakdCrq6HjIbESGr6pacweA2s9SwSxVdjyC+PczaVyZV4HUrkAXHHWN+lfOTE9hK36sQ8O2VIIJFOscrUsoW4oolOwbiEDHDTndAV3khNUhaxr1zpZIsKK0basfeMkd9r0IGaaVsFdmZxhumDAJShmxx3gIRV/GOJf8b6d8Csf/8IRRbCmMxXhNLmEFf7HMIFFO+71kJStvIfhTgpHEBr4bssdnHy7ECfwumnIKwRRyU+A7nEYm6yKN0AHWqq/DNd91ZuY9VBIDQAhqRnbiypPdiR2lcmMryN3Dkuubmn3h4FClF4OajXeF/2aOrCRz5trN8seKhdytWxKZFpo5tk4FcZ3qMfdWspatZDMciWWXHu0XiokAZ3spBGo+Q0smbAiJ5tS9zc17k4tF/pU
  template:
    metadata:
      name: synology-csi
      namespace: synology-csi
