---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synology-csi
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yaml: AgC6NUTSWTrtfiNZHAF8TBP56rw4BdO6AJBQAWuxsjlltK+Xu1ohhqfilsNYFZtZEcC3PWjFU3WtW8BmTU2bTv8OTuM/cBJwGa5EH57tohTYxKCu3qklpXFYOgA6iGyGBEttjMKoU3zyUV0IlChNavJCcU+DCXu6EwJLdK9FhZwLkRK9v8K9zdU2PBd1MKuzW0QD83ueweJcrTwYtjMH4Igl+y8UrcszT+0nEbyhyO/yf7SuEDzSqgLYsoWxF8bgSYIGxP/P1sUrnoC5WriRFrN93fgFW3K/1eWIXEqkpGRq/AQPF5SnNWljko74R57nKamZYcyPHQo4pwlTX4AlghNoR/7iQMKHvrLGCXY+/pKJt4bo5VzP4YYarT5GriUetRnwMpyK8Vw+MsbyNTzBkp80Vy2IJ9KuoYzHUkYEKnRx04n+hWRWXNk5BJpwZVuntZVac2D/eUtR6uZsZe7Z3EzjqF+0JuJjpiBjZsZYMf3lyk2fw3iL85CeAUSqH6CwznFuz/5N79GyBT7uId53u+LJZphaoCkiBHjPR/0Ylh7nF9QSz/GZaZw7GFjwcPIl5DdtFCFHIxV6FfuEBCkAZyzjMZY5S1ifpsyueSc/nP/loz40hFEHER8elsMPpWC+oQFdGlBTXwu/03kjvGar4oGPLxdmhBxrYelKL+yLL0cGHL7n3FgK2XFRHD9meCfBDdAEFCICUnhmNQm2KwRzJy0h7/6oRk4WNaixH9epQWiff9iqvAF9BSQ8CRngCvUSjumQ8ns5MUtcyVDXjzqGWiAp+/p4turDQpeqp5Isupl7LvF7UQXM9xgDGuLwSwKB7JG/CyPNu05u1RvEuRke8Zvk0DaHreiMHzVkdVCWfSD7wg==
  template:
    metadata:
      name: synology-csi
      namespace: synology-csi
