# k8s/asgard/gateway-config/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate-wildcard-niflheim.yaml
  - certificate-wildcard-midgard.yaml
  - certificate-wildcard-apex.yaml
  - gateway-niflheim.yaml
  - gateway-midgard.yaml
