# k8s/asgard/infrastructure/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets
  - synology-csi
  - vault
  - external-secrets
  - metallb
  - authentik
  - gateway-api
