---
all:
  children:
    asgard_k3s:
      children:
        asgard_k3s_cp:
          hosts:
            gondul:
              ansible_host: 10.0.21.11
            hlokk:
              ansible_host: 10.0.21.12
            sigrun:
              ansible_host: 10.0.21.13
        asgard_k3s_workers:
          hosts:
            einherjar-urd:
              ansible_host: 10.0.21.21
            einherjar-verd:
              ansible_host: 10.0.21.22
            einherjar-skuld:
              ansible_host: 10.0.21.23

    asgard_lxcs:
      children:
        factorio_host:
          hosts:
            factorio:
              ansible_host: 10.0.11.220
        postgres_hosts:
          hosts:
            fulla:
              ansible_host: 10.0.11.230
            vor:
              ansible_host: 10.0.11.231
            idunn:
              ansible_host: 10.0.11.232
        haproxy_etcd_hosts:
          hosts:
            hlin:
              ansible_host: 10.0.11.233
            eir:
              ansible_host: 10.0.11.234
            snotra:
              ansible_host: 10.0.11.235
        tailscale_hosts:
          hosts:
            bifrost:
              ansible_host: 10.0.11.213
              tailscale_tag: subnet-router
              tailscale_advertise_routes: 10.0.0.0/16
            heimdall:
              ansible_host: 10.0.11.214
              tailscale_tag: subnet-router
              tailscale_advertise_routes: 10.0.0.0/16
            gjallarbru:
              ansible_host: 10.0.11.215
              tailscale_tag: exit-node
              tailscale_advertise_exit_node: true
        adguard_hosts:
          hosts:
            saga:
              ansible_host: 10.0.11.201
            mimir:
              ansible_host: 10.0.11.202
            kvasir:
              ansible_host: 10.0.11.203
