# k8s/asgard/infrastructure/garage/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - externalsecret.yaml
  - statefulset.yaml
  - services.yaml
  - layout-init-job.yaml
