---
- name: restart postgresql
  ansible.builtin.service:
    name: "postgresql@{{ postgres_version }}-{{ postgres_cluster }}.service"
    state: restarted

- name: reload postgresql
  ansible.builtin.service:
    name: "postgresql@{{ postgres_version }}-{{ postgres_cluster }}.service"
    state: reloaded
