---
- name: systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  listen: reload systemd

- name: restart sftpgo
  ansible.builtin.systemd:
    name: sftpgo.service
    state: restarted
  listen: restart sftpgo
