---
- name: Create factorio group
  ansible.builtin.group:
    name: "{{ factorio_group }}"
    gid: "{{ factorio_gid | default(omit) }}"
    system: true
    state: present

- name: Create factorio user
  ansible.builtin.user:
    name: "{{ factorio_user }}"
    group: "{{ factorio_group }}"
    uid: "{{ factorio_uid | default(omit) }}"
    home: "{{ factorio_home }}"
    create_home: false       # we manage the directory tree ourselves in dirs.yml
    shell: /usr/sbin/nologin
    system: true
    state: present
