# ansible/playbooks/asgard-haproxy-etcd.yml
---
- name: Configure HAProxy/etcd host
  hosts: haproxy_etcd
  become: true

  roles:
    - role: baseline
      tags: [baseline]
    - role: etcd
      tags: [etcd]
    - role: haproxy
      tags: [haproxy]
    - role: keepalived
      tags: [keepalived]
    - role: hardening
      tags: [hardening]
