# ansible/playbooks/haproxy-etcd-host.yml
---
- name: Configure HAProxy/etcd host
  hosts: haproxy_etcd_hosts
  become: true

  roles:
    - role: baseline
      tags: [baseline]
    - role: etcd
      tags: [etcd]
    - role: hardening
      tags: [hardening]
