apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - storage.yaml
  - externalsecret-sonarr.yaml
  - externalsecret-sabnzbd.yaml
  - service.yaml
  - deployment-sonarr.yaml
  - deployment-sabnzbd.yaml
  - middleware-authentik-forward-auth.yaml
  - httproute.yaml
  - recyclarr-config.yaml
  - cronjob-recyclarr.yaml
