# k8s/asgard/infrastructure/authentik/blueprints/00-brand.yaml
version: 1
metadata:
  name: default-brand
entries:
  # Demote the shipped default brand
  - model: authentik_brands.brand
    identifiers:
      domain: authentik-default
    attrs:
      default: false

  # Your domain becomes the default
  - model: authentik_brands.brand
    identifiers:
      domain: authentik.niflheim.xiiisins.com
    attrs:
      branding_title: niflheim
      branding_logo: /static/dist/assets/icons/icon.png
      branding_favicon: /static/dist/assets/icons/icon.png
      flow_authentication:
        !Find [authentik_flows.flow, [slug, default-authentication-flow]]
      flow_invalidation:
        !Find [authentik_flows.flow, [slug, default-invalidation-flow]]
      flow_user_settings:
        !Find [authentik_flows.flow, [slug, default-user-settings-flow]]
      default: true
