# k8s/asgard/synology-csi-config/synology-secret.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: synology-csi
  namespace: synology-csi
spec:
  encryptedData:
    client-info.yaml: AgAzixqePZbpFLCeMKjZaOLc8CmEuOChzN72bgmZGTZoNpNk/uxqaGjl4+bqEBTZseZ0JrzqtAF4ENErqDXQHnYpEEbe7GjZxvjGZR5dDzEhp2y61pmEqWVviBBgLfT1Eib4Jh+C+6RCi1A04HPBSFBGb0UxXHKHvtIVkpPsIBrnEevPgZsJaF5G2gn5lCZEMrpTiS30O4oTAQZ41OUfZHk/Ou3HeJv3YUgGb2giXiS20uQw9jqkD5an61Nbk1bfbSnf0dJINISvWUc2GG4aeZPFK8UYdBqGp/a5Z+B0bSIA3mKqgnZ+QUvwLhUdf93vGIlECfmuidd+YcOqnL00F9H99vqICns7LBUx6xD+GOod615xllXJHSmUcIS75Sl0jaT/nxwuKCHNp/CCkaRK1XXiL/UEnBlW73w8S/4Sqfl7m9fXd0CVpL4Tr5M+NXW9Uo0tQPEo10Tum5Kp4crO7BJUy+2ctE3O2qMIj0ng/2PvQA7RbQEbouBIVeassMkY9gfBwBCW2B3MsOZurNtPgPappdTqxgXM8g2tu6eKSFVQxJIY8qL8BYGBy8rs5ccdhbLfyutdY+8BXbJcUlW9dARQCdronrTtkR0HaMkN/cu9BTI4ateDgkS/SfQHXkKraVPutI4m5bE/Q3an2Vy3BGFZ9L4Tc1VV3xNNiEd3zmA78O9KzY4sD1K6SvbzalTKexui1mKphW/5tfsp5/v7zyGQgwUqiyxyDjVefTnixU0rOeMmfwEvGVUYi6wQJxShN33hGRwmp7KGj9fDTKKNo53X78JACAEqZ6Kdi2qXcuXY0+UpDgQzTsd/LDjr+Xn307qtqeCBsLAIEBBxetXvaTBk4P4uX4MseG/t/A==
  template:
    metadata:
      name: synology-csi
      namespace: synology-csi
