# k8s/asgard/vpa-config/overview.yaml
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: overview
  namespace: overview
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: overview
  updatePolicy:
    updateMode: "Off"
