# k8s/asgard/vpa-config/synology-csi.yaml
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: synology-csi-controller
  namespace: synology-csi
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: synology-csi-controller
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: synology-csi-node
  namespace: synology-csi
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: synology-csi-node
  updatePolicy:
    updateMode: "Off"
