# ansible/roles/vlagent/handlers/main.yml
---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart vlagent
  ansible.builtin.systemd:
    name: vlagent.service
    state: restarted
